name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-deps:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: law-firm-saas/package-lock.json

      - name: Install dependencies
        working-directory: law-firm-saas
        run: npm ci

  typecheck:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: law-firm-saas/package-lock.json

      - name: Install dependencies
        working-directory: law-firm-saas
        run: npm ci

      - name: Run TypeScript type check
        working-directory: law-firm-saas
        run: npx tsc --noEmit

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: law-firm-saas/package-lock.json

      - name: Install dependencies
        working-directory: law-firm-saas
        run: npm ci

      - name: Run ESLint
        working-directory: law-firm-saas
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: law-firm-saas/package-lock.json

      - name: Install dependencies
        working-directory: law-firm-saas
        run: npm ci

      - name: Build Next.js application
        working-directory: law-firm-saas
        run: npm run build

  supabase-lint:
    name: Supabase Database Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Run Supabase database lint
        working-directory: law-firm-saas
        run: supabase db lint
